# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f71ebe61baf113887301aac23d9dc903cf4ba98cec3b1979db01a86b005f2be021ce84def00f6fb449d4020c5e59e5d5d9e1380df4525f02a3cce16ddd728ae8

test:
  secret_key_base: aced00d0ddcd15fa76f95ca762337d6296879cb03ed19d5281e03031c5fae54fbb2564f32a47809507d209108f62b2d7a4db6cbff42667942dd3f54d7c48ef12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
